apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-app-chart.fullname" . }}
data:
  DB_HOST: {{ include "mysql.fullname" . }}
  DB_PORT: {{ .Values.mysql.service.port | quote }}
  DB_NAME: {{ .Values.mysql.db.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sa-app-chart.fullname" . }}
type: Opaque
data:
  DB_USER: {{ .Values.mysql.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.mysql.db.password | b64enc }}