apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sa-app-chart.fullname" . }}
  labels:
    {{- include "sa-app-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      initContainers:
      - name: check-db-ready
        image: busybox:1.28
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "sa-app-chart.fullname" . }}
                key: DB_HOST
        command: ['sh', '-c', "until nslookup $(DB_HOST).$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for db; sleep 2; done"]
      containers:
      - name: apply-db-migrations
        image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
        imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "sa-app-chart.fullname" . }}
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "sa-app-chart.fullname" . }}
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "sa-app-chart.fullname" . }}
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "sa-app-chart.fullname" . }}
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "sa-app-chart.fullname" . }}
                key: DB_NAME
