apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-course-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-course-app
  template:
    metadata:
      labels:
        app: sa-course-app
    spec:
      containers:
        - name: sa-course-app
          image: andyovch/sa-course-app:master
          imagePullPolicy: "Always"
          env:
            - name: SAAPP_PORT
              value: "8000"
            - name: SAAPP_DB_HOST
              value: "mysql"
            - name: SAAPP_DB_PORT
              value: "3306"
            - name: SAAPP_DB_USER
              value: "root"
            - name: SAAPP_DB_PASSWORD
              value: "12345Q"
            - name: SAAPP_DB_NAME
              value: "sa-app"
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: web
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: web
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5