apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  template:
    metadata:
      name: db-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrations-job
          image: andyovch/sa-course-app-migrations:v1
          imagePullPolicy: "Always"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
  backoffLimit: 2
